### ISSUE TITLE
Badoo Star Bar

### ISSUE THREAD

**Issue by spennyf** [danthorpe/DNTFeatures#21]
@danthorpe  hey man I saw you were watchin Badoo/StarBar and sorry to bother you but I got a quick quesiton, and have it all set up and working expect that when I pick a star that star isn't save, in other words it goes back to the default state where all the stars are unselected... And I am not canceling the rating as I check that, how do I save the number of stars that are selected thanks so much for your help. Have a good day :)

**Comment by danthorpe** [comment]
Hi @spennyf I think it's probably best if you create an issue on the Badoo/StarBar repo here: https://github.com/badoo/StarBar

**Comment by spennyf** [comment]
hi there I have created a issue on the StarBar, do you know how to fix this though?

**Comment by danthorpe** [comment]
Sorry, no, I don't use this code. I watch many repositories.
